- name: intall nginx and run
  hosts: frontend
  become: yes # sudo access 
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes

