- name: configuring catalogue component
  become: yes
  hosts: catalogue
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs module
    ansible.builtin.dnf: 
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create a app dirctory 
    ansible.builtin.file:
      path : /app
      state: dirctory

  - name: download the code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
      
  - name: Extract the code 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes





  






