- name: installing frontend component ( nginx)
  become: yes
  hosts: frontend
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y
  - name: enable nginx 
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: installing nginx 
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: directory
  
  - name: download the frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src : yes
  - name: remove the directory
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx configutation 
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  
