- name: configuring mysql component
  become: yes
  hosts: mysql
  tasks:
  - name: installing mysql database
    ansible.builtin.dnf:
      name:  mysql-server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    