- name: install user component
  hosts: user
  become: yes
  tasks:
  - name: disable default redis version
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name: enable redis -7 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create a app dirctory 
    ansible.builtin.file:
      path : /app
      state: directory 

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download the code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: Extract the user code 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
      
  - name: Install dependencies from package.json
    community.general.npm:
      path: /app
  
  - name: copy user service to systemd
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service


  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true


  - name: start and enable service module
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes


