- name: install redis component
  hosts: redis
  become: yes
  tasks:
  - name: disable default redis version
    ansible.builtin.command: dnf module disable redis -y 
    
  - name: enable redis -7 version
    ansible.builtin.command: dnf module enable redis:7 -y
  
  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: allow remote connections over the internet
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: disable protect mode 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no

  - name: start and enable the redis
    ansible.builtin.service:
      name: redis 
      state: started
      enabled: yes
